
import { Header } from "@/src/components/header";
import "@/styles/globals.css";
import { SessionProvider } from "next-auth/react";
import Head from "next/head";
import { session } from "next-auth/react";


export default function App({ Component, pageProps:{session, ...pageProps} }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <SessionProvider session={session}>
         <Component {...pageProps} />
      </SessionProvider>
     
     
    </>
  );
}
